### ISSUE TITLE
请问是不是少传文件了

### ISSUE THREAD

**Issue by qq88797833** [ouxianghui/mediasoup-client#1]
![image](https://user-images.githubusercontent.com/28855943/167296625-f43d3f2d-8f55-4bd5-9c2c-78ac374f5b2d.png)
![image](https://user-images.githubusercontent.com/28855943/167296652-1e3fc95f-4809-4baf-8fc9-b8cefd5aa341.png)

**Comment by ouxianghui** [comment]
已上传
