### ISSUE TITLE
基于windows 平台编译文件找不到（webrtc m112）

### ISSUE THREAD

**Issue by samegame** [ouxianghui/mediasoup-client#8]
![微信截图_20231218105556](https://github.com/ouxianghui/mediasoup-client/assets/37954473/4005d49b-6c85-4ff3-8e60-a73161eaf6ae)
![微信截图_20231218105624](https://github.com/ouxianghui/mediasoup-client/assets/37954473/9f615056-098c-4ab6-b250-c2f8e3c224a6)

**Comment by ouxianghui** [comment]
太大了，没上传。你可以自己下载或编译

**Comment by ouxianghui** [comment]
太大了，没上传。你可以自己下载或编译

**Comment by samegame** [comment]
webrtc.lib库是已下载源码编译出来了，但在m112版本源码中没找到上面缺失的相关文件

**Comment by samegame** [comment]
已适配m112版本，感谢！

**Comment by wangdemon** [comment]
> 已适配m112版本，感谢！

我用m112，编译也是一推错误，请问webrtc是哪个版本
